### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Wally73** [Pixelz/eggdrop-github#1]
trying to get this to work with eggdrop 1.8.3

Configured with: '--with-tcllib=/opt/ActiveTcl-8.6/lib/libtcl8.6.so' '--with-tclinc=/opt/ActiveTcl-8.6/include/tcl8.6/tcl.h'
OS: Linux 3.16.0-4-amd64
Tcl library: /usr/share/tcltk/tcl8.6
Tcl version: 8.6.9 (header version 8.6.4)
Tcl is threaded.
TLS support is enabled.
TLS library: OpenSSL 1.1.1  11 Sep 2018

getting the following errors

[13:14:13] Tcl error in file 'gitbot.conf':
[13:14:13] invalid command name "settingsFileOk"
    while executing
"settingsFileOk"
    (procedure "loadSettings" line 4)
    invoked from within
"loadSettings"
    (in namespace eval "::github" script line 14)
    invoked from within
"namespace eval ::github {
	if {![info exists initDone]} {
		socket -server ::github::acceptConnection $port
		set initDone 1
	}

	# Make sure we're us..."
    (file "scripts/github.tcl" line 1636)
    invoked from within
"source scripts/github.tcl"
    (file "gitbot.conf" line 1483)

also there isn't a github.tcl.settings file in the repo

**Comment by Wally73** [comment]
also tried with eggdrop 1.6.21 
same errors

**Comment by thezoggy** [comment]
```[22:05:32] Tcl error in file 'eggdrop.conf':
[22:05:32] invalid command name "settingsFileOk"
    while executing
"settingsFileOk"
    (procedure "loadSettings" line 4)
    invoked from within
"loadSettings"
    (in namespace eval "::github" script line 14)
    invoked from within
"namespace eval ::github {
	if {![info exists initDone]} {
		socket -server ::github::acceptConnection $port
		set initDone 1
	}

	# Make sure we're us..."
    (file "scripts/github.tcl" line 1636)
    invoked from within
"source scripts/github.tcl"
    (file "eggdrop.conf" line 1549)
[22:05:32] * CONFIG FILE NOT LOADED (NOT FOUND, OR ERROR)
```

due to: `settingsFileOk` not being valid anymore:
```
proc ::github::loadSettings {} {
        variable settingsFile
        variable settings
        if {[settingsFileOk]} {
                if {[catch {open $settingsFile r} fd]} {
                        putlog "github.tcl Error: failed to open settings file: $fd"
```

looks like `proc ::github::settingsFileOk` was removed in lieu of `proc ::github::isFileOk`

**Comment by Pixelz** [comment]
Fixed now, sorry for taking so long.
